[package]
name = "lfsr-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lfsr = { path = "../lib" }
clap = { version = "4", features = ["derive"] }

[[bin]]
name = "lfsr"
path = "src/main.rs"
