[package]
name = "lfsr-wasm"
version = "0.1.0"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lfsr = { path = "../lib" }
wasm-bindgen = "0.2"
