[package]
name = "lfsr"
version = "0.1.0"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.17"

[dev-dependencies]
indoc = "0.3"
pretty_assertions = "0.6"
